byol-x86: "6njl1pau431dv1qxipg63mvah"
byol-arm: "70xbkm08ivye46l4gfa6c85v7"
byol-x86-ai-runtime: "b261y39exndwe1ltro1tqpeog"
paygo-x86-bundle1: "e9yfvyj3uag5uo5j2hjikv74n"
paygo-x86-bundle2: "hd44w1chf26uv4p52cdynb2o"
paygo-arm-bundle2: "3qxryq2rjnyddvecce0pvhf2j"
